export const PortfolioData = [
    {
        id:1,
        title:'All Stacked Up',
        category:['other'],
        img:'/images/all-stacked-up-img.PNG',
        tags:['Construction', 'Front End'],
        link:'https://allstackedup.com/',
        mobileImage:'/images/portfolio/mobile/blackfish.png',
        text:'',
        animation:''
    },
    {
        id:2,
        title:'Atlas Staffing',
        category:['other'],
        img:'/images/portfolio/atlas-staffing.PNG',
        tags:['Front End', 'Staffing'],
        link:'https://www.atlasstaffinginc.com/',
        mobileImage:'/images/portfolio/mobile/atlas-staffing.png',
        text:'',
        animation:''
    },
    {
        id:3,
        title:'Big Frig',
        category:['shopify'],
        img:'./images/portfolio/bigfrig-img.PNG',
        tags:['shopify', 'Product Management','front end'],
        link:'https://www.bigfrig.com/',
        mobileImage:'/images/portfolio/mobile/bigfrig.png',
        text:'',
        animation:''
    },
    {
        id:4,
        title:'BlackFish Gear',
        category:['magento','other'],
        img:'./images/portfolio/blackfish.PNG',
        tags:['E-Commerce','front end','magento'],
        link:'https://www.blackfishgear.com/',
        mobileImage:'/images/portfolio/mobile/.png',
        text:'',
        animation:''
    },
    {
        id:5,
        title:'Clam Outdoors',
        category:['magento','featured','other'],
        img:'./images/portfolio/clam-img.PNG',
        tags:['front end','designer'],
        link:'https://www.clamoutdoors.com/',
        mobileImage:'/images/portfolio/mobile/clam.png',
        text:'',
        animation:''
    },
    {
        id:6,
        title:'Cord Sets',
        category:['other','featured'],
        img:'./images/portfolio/cord-sets-img.PNG',
        tags:['front end','animation','design'],
        link:'https://cordsetsinc.com/',
        mobileImage:'/images/portfolio/mobile/cordsets.png',
        text:'',
        animation:''
    },
    {
        id:7,
        title:'Devils Lake',
        category:['featured','other'],
        img:'./images/portfolio/devils-lake-img.PNG',
        tags:['design','develop'],
        link:'https://devilslakend.com/',
        mobileImage:'/images/portfolio/mobile/.png',
        text:'',
        animation:''
    },
    {
        id:8,
        title:'Fiocchi Ammo',
        category:['featured','magento'],
        img:'./images/portfolio/fiocchi-img.PNG',
        tags:['data managment','front end','back end','multi-lingual'],
        link:'https://fiocchi.com/',
        mobileImage:'/images/portfolio/mobile/.png',
        text:'',
        animation:''
    },
    {
        id:9,
        title:'Fishlectronics',
        category:['other'],
        img:'./images/portfolio/fishlectronics-img.PNG',
        tags:['bigcommerce','development'],
        link:'https://fishlectronics.com/',
        mobileImage:'/images/portfolio/mobile/fishlectronics.png',
        text:'',
        animation:''
    },
    {
        id:10,
        title:'Floor Tool Store',
        category:['shopify'],
        img:'./images/portfolio/floor-tool-store.PNG',
        tags:['data management','design','develop'],
        link:'https://www.floortoolstore.com/',
        mobileImage:'/images/portfolio/mobile/floortoolstore.png',
        text:'',
        animation:''
    },
    {
        id:11,
        title:'Frying Saucer',
        category:['wordpress'],
        img:'./images/portfolio/fryin-saucer-img.PNG',
        tags:['wordpress','develop'],
        link:'https://www.thefryinsaucercompany.com/',
        mobileImage:'/images/portfolio/mobile/fryingsaucer.png',
        text:'',
        animation:''
    },
    {
        id:12,
        title:'Gator Eyes',
        category:['other'],
        img:'./images/portfolio/gator-eyes.PNG',
        tags:['E-Commerce','design','animation'],
        link:'https://gatoreyeslights.com/',
        mobileImage:'/images/portfolio/mobile/.png',
        text:'',
        animation:''
    },
    {
        id:13,
        title:'GC Hockey',
        category:['other','featured'],
        img:'./images/portfolio/gchockey-img.PNG',
        tags:['design','concrete 5'],
        link:'https://www.gchockey.com/',
        mobileImage:'/images/portfolio/mobile/.png',
        text:'',
        animation:''
    },
    {
        id:14,
        title:'Howes Fishing',
        category:['other'],
        img:'./images/portfolio/howes-fishing-img.PNG',
        tags:['design','develop'],
        link:'https://www.howesfishing.com/',
        mobileImage:'/images/portfolio/mobile/.png',
        text:'',
        animation:''
    },
    {
        id:15,
        title:'Twin Cities Film Fest',
        category:['wordpress','featured'],
        img:'./images/portfolio/twincities-img.PNG',
        tags:['streaming service','design','AWS servers'],
        link:'https://www.twincitiesfilmfest.org/',
        mobileImage:'/images/portfolio/mobile/.png',
        text:'',
        animation:''
    },
    {
        id:16,
        title:'Operator Coffee',
        category:['shopify','featured'],
        img:'./images/portfolio/operator-coffee.PNG',
        tags:['shopify','design','product management'],
        link:'https://www.operatorcoffee.com/',
        mobileImage:'/images/portfolio/mobile/.png',
        text:'',
        animation:''
    },
    {
        id:17,
        title:'The MN Table',
        category:['wordpress','featured'],
        img:'./images/portfolio/mntable-img.PNG',
        tags:['E-Commerce','Animation','Delviery Service'],
        link:'https://www.themntable.com/',
        mobileImage:'/images/portfolio/mobile/.png',
        text:'',
        animation:''
    },
    {
        id:18,
        title:'TechWear USA',
        category:['magento','featured'],
        img:'./images/portfolio/techwear-img.PNG',
        tags:['design'],
        link:'https://techwearusa.com/',
        mobileImage:'/images/portfolio/mobile/.png',
        text:'',
        animation:''
    },
    {
        id:19,
        title:'I94 West Chamber',
        category:['wordpress','featured'],
        img:'./images/portfolio/i94west-chamber.PNG',
        tags:['design','develop'],
        link:'https://i94westchamber.org/',
        mobileImage:'/images/portfolio/mobile/.png',
        text:'',
        animation:''
    },
    {
        id:20,
        title:'IDS Suites',
        category:['other'],
        img:'./images/portfolio/ids-suits-img.PNG',
        tags:['other','design','develop'],
        link:'https://ids-executivesuites.com/',
        mobileImage:'/images/portfolio/mobile/.png',
        text:'',
        animation:''
    },
    {
        id:21,
        title:'Lucys Burgers',
        category:['other'],
        img:'./images/portfolio/lucys-burgers.PNG',
        tags:['Multi Location','Design','Develop'],
        link:'https://lucysburgers.com/',
        mobileImage:'/images/portfolio/mobile/.png',
        text:'',
        animation:''
    },
    {
        id:22,
        title:'National Recoveries',
        category:['wordpress'],
        img:'./images/portfolio/nri-image.PNG',
        tags:['developer'],
        link:'https://nationalrecoveries.com/',
        mobileImage:'/images/portfolio/mobile/.png',
        text:'',
        animation:''
    },
    {
        id:23,
        title:'Pinky Swear',
        category:['wordpress'],
        img:'./images/portfolio/pinky-swear.PNG',
        tags:['Non-profit','develop','design'],
        link:'https:/pinkyswear.org/',
        mobileImage:'/images/portfolio/mobile/.png',
        text:'',
        animation:''
    },
    {
        id:24,
        title:'Polar Trailers',
        category:['magento','other'],
        img:'./images/portfolio/polar-img.PNG',
        tags:['E-Commerce','design','develop'],
        link:'https://polartrailer.com/',
        mobileImage:'/images/portfolio/mobile/.png',
        text:'',
        animation:''
    },
    {
        id:25,
        title:'Roberts Fine Jewlery',
        category:['other'],
        img:'./images/portfolio/robers-img.PNG',
        tags:['design','develop'],
        link:'https://robertsfinejewelry.net/',
        mobileImage:'/images/portfolio/mobile/.png',
        text:'',
        animation:''
    },
    {
        id:26,
        title:'The Visor Guy',
        category:['wordpress'],
        img:'./images/portfolio/the-visor-guy-img.PNG',
        tags:['animation','develop','E-Commerce'],
        link:'https://thevisorguy.com/',
        mobileImage:'/images/portfolio/mobile/.png',
        text:'',
        animation:''
    },
    {
        id:27,
        title:'Triggerd',
        category:['wordpress'],
        img:'./images/portfolio/triggered-img.PNG',
        tags:['develop','design'],
        link:'https://triggerdexpo.com/',
        mobileImage:'/images/portfolio/mobile/.png',
        text:'',
        animation:''
    },
    {
        id:28,
        title:'Vexilar',
        category:['magento'],
        img:'./images/portfolio/vexilar-img.PNG',
        tags:['E-Commerce','frontend','Data Managment'],
        link:'https://vexilar.com/',
        mobileImage:'/images/portfolio/mobile/.png',
        text:'',
        animation:''
    },
    {
        id:29,
        title:'Wagner Construction',
        category:['other','featured'],
        img:'./images/portfolio/wagner-img.PNG',
        tags:['construction'],
        link:'https://wagnerconstructionmn.com/',
        mobileImage:'/images/portfolio/mobile/.png',
        text:'',
        animation:''
    },
    {
        id:30,
        title:'Duo Kings',
        category:['wordpress'],
        img:'./images/.PNG',
        tags:['small business','construction','design/develop'],
        link:'https://duo-kings.com/',
        mobileImage:'/images/portfolio/mobile/.png',
        text:'',
        animation:''
    }

]